syntax = "proto3";

package social.posts;

option java_multiple_files = true;
option java_outer_classname = "PostsProto";
option java_package = "org.alexcawl.contract.posts.proto";

import "entity.proto";

service PostsService {
  rpc CreatePost(CreatePostRequest) returns (CreatePostResponse);
  rpc ListFeed(ListFeedRequest) returns (ListFeedResponse);
}

message CreatePostRequest {
  string author_id = 1;
  string text = 2;
}

message CreatePostResponse {
  oneof result {
    entity.Post post = 1;
    entity.Failure validation_failure = 2;
    entity.Failure not_found_failure = 3;
  }
}

message ListFeedRequest {}

message ListFeedResponse {
  oneof result {
    entity.Feed feed = 1;
    entity.Failure validation_failure = 2;
  }
}
